accounts/urls.py
from django.urls import path
from .views import  SignupmakerView, SignupCheckerView,login_View, logout_view

app_name='accounts'
urlpatterns=[
  # accounts/signup/
  path('maker/',SignupmakerView.as_view(), name='signupmaker'),
  path('checker/',SignupCheckerView.as_view(), name='signupchecker'),
  path('login/', login_View, name='login'),
  path('logout/', logout_view, name='logout'),



]

mediafile/urls.py
from django.urls import path
from .views import uploadfile_createView, uploadfile_listView, detailview, updateview, deleteview

app_name='files'
urlpatterns = [
  path('create/',uploadfile_createView.as_view(),name='create' ),
  path('list/',uploadfile_listView.as_view(),name='list' ),
  path('detail/<int:pk>/', detailview ,name='detail'),
  path('update/<int:pk>/', updateview.as_view() ,name='update'),
  path('delete/<int:pk>/', deleteview.as_view(),name='delete'),
]

task1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',SignupView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('files/', include('mediafile.urls', namespace='files')),


    
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
  is_maker = models.BooleanField(default=False)
  is_checker = models.BooleanField(default=False)
  confirm_password = models.CharField(max_length=120, blank=True)
  # confirm_password set blank because i have already create a database and it ask to set default value so

mediafile/models.py
from django.db import models
from accounts.models import User
import os 

class UploadFile(models.Model):
  TypeOfFile=(
    (1,'Image'),
    (2, 'pdf'),
    (3, 'Video')

  )
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  title = models.CharField(max_length=150)
  created_on = models.DateTimeField(auto_now_add=True)
  updated_on = models.DateTimeField(auto_now=True)
  file = models.FileField()
  Type = models.IntegerField(choices=TypeOfFile, null=True)

  class Meta:
    ordering = ['-created_on']





class Comment(models.Model):
  mediafile = models.ForeignKey(UploadFile, on_delete=models.CASCADE)
  created_on = models.DateTimeField(auto_now_add=True)
  name = models.CharField(max_length=150, blank=True)
  body = models.TextField()
  
  class Meta:
    ordering = ['-created_on']

  def __str__(self):
    return 'Comment {} by {}'.format(self.body, self.name)

accounts/forms.py
from django import forms
from .models import User

class SignupmakerForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ['first_name', 'last_name','username', 'email', 'password', 'confirm_password']

  def clean_username(self):
    if User.objects.filter(username=self.cleaned_data['username']).exists():
      raise forms.ValidationError("Username is already taken")
    return self.cleaned_data['username']

  def clean(self):
    password = self.cleaned_data['password']
    confirm_password = self.cleaned_data['confirm_password']
    if password != confirm_password:
      raise forms.ValidationError("Your password doesnot match!!")

  
  def save(self):
    user = super().save(commit=False)
    user.set_password(self.cleaned_data['password'])
    user.is_maker = True
    user.save()
    return user

class SignupCheckerForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['first_name', 'last_name','username', 'email', 'password', 'confirm_password']

  def clean_username(self):
    if User.objects.filter(username=self.cleaned_data['username']).exists():
      raise forms.ValidationError("Username is already taken")
    return self.cleaned_data['username']

  def clean(self):
    password = self.cleaned_data['password']
    confirm_password = self.cleaned_data['confirm_password']
    if password != confirm_password:
      raise forms.ValidationError("Your password doesnot match!!")

  
  def save(self):
    user = super().save(commit=False)
    user.set_password(self.cleaned_data['password'])
    user.is_checker = True
    user.save()
    return user

class loginForm(forms.Form):
  username = forms.CharField(max_length=120)
  password = forms.CharField(max_length=120, widget=forms.PasswordInput())
  

mediafile/forms.py
from django import forms
from .models import UploadFile, Comment

class FileCreateForm(forms.ModelForm):
  class Meta:
    model = UploadFile
    fields = [ 'title','file', 'Type']
  
  # def save(self):
  #   filedata = super().save(commit=False)
  #   filedatatype = self.cleaned_data['file']
  #   filename = filedatatype.name

  #   def checkfiletype():
  #     if filename.endswith('.pdf'):
  #       return 1
  #     elif filename.endswith('.png'):
  #       return 2
  #     else:
  #       return 3

  #   filedata.fileoffile = checkfiletype
  #   filedata.save()
  #   return filedata
    


class commentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['name','body']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView
from .models import User
from .forms import SignupmakerForm, SignupCheckerForm
from .forms import loginForm
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth import get_user_model

USER = get_user_model()
class SignupView(TemplateView):
  template_name = 'accounts/home.html'


class SignupmakerView(CreateView):
  form_class = SignupmakerForm
  template_name = 'accounts/makersignup.html'
  success_url = '/accounts/login'


class SignupCheckerView(CreateView):
  form_class = SignupCheckerForm
  template_name = 'accounts/checkersignup.html'
  success_url = '/accounts/login'




def login_View(request):
  if request.method == 'POST':
    form = loginForm(request.POST)
    if form.is_valid():
      user = authenticate(username = form.cleaned_data['username'],
                          password = form.cleaned_data['password'])
      if user:
        print("User is found")
        login(request,user)
        return redirect('/files/list')

      else:
        print("User isnot found")
  elif request.method == 'GET':
    form = loginForm()
  return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
  logout(request)
  return redirect('/accounts/login')

mediafile/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .forms import FileCreateForm, commentForm
from .models import UploadFile, Comment
from accounts.decorators import maker_required, checker_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
# @maker_required
class uploadfile_createView(CreateView):
  template_name = 'mediafile/create.html'
  form_class = FileCreateForm
  success_url = '/files/list/'

  def form_valid(self, form):
    self.object = form.save(commit=False)
    self.object.author = self.request.user
    self.object.save()
    return super().form_valid(form)


class uploadfile_listView(ListView):
  template_name = 'mediafile/list.html'
  model = UploadFile
  context_object_name = 'data'
  queryset = UploadFile.objects.all()



@method_decorator(login_required, name='dispatch')
class updateview(UpdateView):
  form_class = FileCreateForm
  success_url = '/files/list/'
  model = UploadFile
  template_name = 'mediafile/update.html'


# @checker_required
@method_decorator(login_required, name='dispatch')
class deleteview(DeleteView):
  model = UploadFile
  success_url = '/files/list'

  def get(self, request, *args, **kwargs):
    return self.post(request, *args, **kwargs)


def detailview(request, pk):
  template_name = 'mediafile/detail.html'
  post = get_object_or_404(UploadFile, id=pk)
  comments = Comment.objects.filter(mediafile_id = pk)
  new_comment = None
  # Comment posted
  if request.method == 'POST':
    comment_form = commentForm(request.POST)
    if comment_form.is_valid():
      new_comment = comment_form.save(commit=False)
      new_comment.mediafile_id = post.id
      new_comment.save()
  else:
    comment_form = commentForm()
  return render(request, template_name, {'post': post,'comments':comments, 'new_comment': new_comment,'comment_form': comment_form})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>UploadFile</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <style>
      body {
      font-family: "Roboto", sans-serif;
      font-size: 17px;
      background-color: #e5e5e5;
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
      margin:0;
      height: 100vh;
      }
      .shadow {
          box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
      }
      .btn-danger {
        
          background-color: #f00000;
          border-color: #dc281e;
      }
      h1, li, a{font-family:Times New Roman;}

    .btn{
      margin:15px
    }
    .navbar{
      overflow: hidden;
      background-color: #f5f5f5;
      width: 100%;
  
    
    }
    .col-3{
      background-color: white;
      height: 90vh;
  
    }
  .navbar {
  overflow: hidden;
  position: fixed;
  top: 0;
  width: 100%;
}


</style>
<nav class="navbar navbar-expand-lg navbar-light bg" id="mainNav">
  <div class="container-fluid">
    <a class="navbar-brand font-weight-bold " href="{% url 'home' %}">Home</a>
    <a class="navbar-brand font-weight-bold " href="{% url 'files:list' %}">Media File</a>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item text-black">
                <a class="nav-link font-weight-bold" href="#">About</a>
            </li>
            <li class="nav-item text-black">
                <a class="nav-link font-weight-bold" href="#">Contact</a>
            </li>
            <li class="nav-item text-black">
              <a class="nav-link  font-weight-bold" href="{% url 'accounts:login' %}">Login </a>
          </li>
        </ul>
    </div>
  </div>
 </nav>
 
{% block content %}

{% endblock %}
  
</body>
</html>

accounts/templates/accounts/checkersignup.html
{% extends 'accounts/base.html' %}
{% block content %}
<style>
  .container{
  background-color:#e5e5e5;
}
.sign{
  margin-top: 20px;margin-left: 25%;
}
.card{

  padding: 30px; border-radius: 10px; width:50%; margin:auto;
  position: static;
}
.btn{
  background-color: #4373d9;
  width:20%
}
body{
  margin-top: 50px;
  position: static;
}
</style>

<body class="container">
  <h1  class="sign" style="font-family:Times New Roman;">SignUp as checker</h1>
  <div class="card">
      <form method="post" action="/accounts/maker/">
        {% csrf_token %}
          <div class="form-group">
              <label>First Name</label>
              <input type="text" class="form-control" placeholder="First Name" name="first_name" required>
          </div>
          <div class="form-group">
            <label>Last Name</label>
            <input type="text" class="form-control" placeholder="Last Name" name="last_name" required>
          </div>
          <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" placeholder="Username" name="username" required>
         </div>
         <div class="form-group">
          <label>Email</label>
          <input type="text" class="form-control" placeholder="Email" name="email" required>
        </div>
          <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control"  name="password" required>
          </div>
          <div class="form-group">
              <label for="password">Confirm Password</label>
              <input type='password' class="form-control" name="confirm_password" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  </div>
  
  </body>
  {% endblock %} 

accounts/templates/accounts/home.html
{% extends "accounts/base.html" %}

{% block content %}

<style>
    .col-3{
    margin-top: 4vw;
    position: absolute;;
    }
    
</style>

<div class="col-3">
  {% block sidebar %} 
  {% include 'accounts/sidebar.html' %}
  {% endblock %}
</div>



{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}
<style>
  .container{
  background-color:#e5e5e5;
}
.sign{
  margin-top: 20px;margin-left: 25%;
  
}
.card{

  padding: 30px; border-radius: 10px; width:50%; margin:auto;
  position: static;
}
.btn{
  background-color: #4373d9;
  width:20%
}
body{
  margin-top: 50px;
  position: static;
}

</style>

<body class="container">
  <h1  class="sign" style="font-family:Times New Roman;">Login Form</h1>
  <div class="card">
      <form method="post">
        {% csrf_token %}  
          <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" placeholder="Username" name="username" required>
         </div>
          <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control"  name="password" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  </div>
  
  </body>
  {% endblock %}

accounts/templates/accounts/makersignup.html
{% extends 'accounts/base.html' %}
{% block content %}
<style>
  .container{
  background-color:#e5e5e5;
}
.sign{
  margin-top: 20px;margin-left: 25%;
}
.card{

  padding: 30px; border-radius: 10px; width:50%; margin:auto;
  position:static
}
.btn{
  background-color: #4373d9;
  width:20%
}
body{
  margin-top: 50px;
  position: static;
}
</style>

<body class="container">
  <h1  class="sign" style="font-family:Times New Roman;">SignUp as Maker</h1>
  <div class="card">
      <form method="post" action="/accounts/maker/">
        {% csrf_token %}
          <div class="form-group">
              <label>First Name</label>
              <input type="text" class="form-control" placeholder="First Name" name="first_name" required>
          </div>
          <div class="form-group">
            <label>Last Name</label>
            <input type="text" class="form-control" placeholder="Last Name" name="last_name" required>
          </div>
          <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" placeholder="Username" name="username" required>
         </div>
         <div class="form-group">
          <label>Email</label>
          <input type="text" class="form-control" placeholder="Email" name="email" required>
        </div>
          <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control"  name="password" required>
          </div>
          <div class="form-group">
              <label for="password">Confirm Password</label>
              <input type='password' class="form-control" name="confirm_password" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  </div>

  
  </body>
  {% endblock %} 

accounts/templates/accounts/sidebar.html
{% block sidebar %}

<style>

.sidebar a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}



.sidebar a:hover {
  color: blue;


}
.sidebar{
  margin-left: 20px;
  margin-top: 20px;
}
#demo{
  margin-left: 15px;
}
</style>

  <div class="sidebar">
    <a href = "#" >Dashboard</a>
    <a href="#" data-toggle="collapse" data-target="#demo">Sign Up</a>
    <div id="demo" class="collapse">
      <a href="{% url 'accounts:signupmaker' %}" >Maker</a>
      <a href="{% url 'accounts:signupchecker' %}" >Checker</a>
    </div>
    <a href ="{% url 'files:create' %}">Upload File</a>
  </div>



{% endblock %}

mediafile/templates/mediafile/create.html
{% extends 'accounts/base.html' %}
{% block content %}
<style>
  .container{
  background-color:#7a3f79;
}
.sign{
  margin-top: 20px;margin-left: 25%;color:white; 
}
.card{

  padding: 30px; border-radius: 10px; width:50%; margin:auto
}
.btn{
  background-color: #4373d9;
  width:20%
}
</style>

<body class="container">
  <h1  class="sign" style="font-family:Times New Roman;">Upload File</h1>
  <div class="card">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
          <div class="form-group">
              <label>Title</label>
              <input type="text" class="form-control" placeholder="Title" name="title" required>
          </div>
          <div class="form-group">
            <label>File</label>
            <input type="file" class="form-control" placeholder="Upload File" name="file" required>
          </div>

          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  </div>
  
  </body>
  {% endblock %} 


 

mediafile/templates/mediafile/detail.html
{% extends 'accounts/base.html' %}

{% block content %}
<style>
  .container{
    color:white
  }
hr{
    color: white;
}

h1{
    text-align: center;
}

h1, li, a{font-family:Times New Roman;}

h2{
  text-align: left;
}

.sign{
  margin-top: 20px;margin-left: 25%;color:white; 
}
.card{

  padding: 30px; border-radius: 10px; width:50%;
  margin:25px;
  margin-left:15px;
}
label{
  color:black
}
img{
  width: 350px;
  height: 400px;
  text-align: center;
       
    }

.col-9{
    margin-top: 60px;
    margin-left: 25vw;
    position:static;
}
    .col-3{
  margin-top: 4vw;
  position: fixed;
}

.row-1{
    margin-left: 2px;
}


</style>
<div class='row'>
  <div class='col-3'>
    {% block sidebar %}
    {% include 'accounts/sidebar.html' %}
    {% endblock %}
  </div>

  <div class ='col-9 comments'>
    <h1>Detail and Comments of file</h1>
    {% if request.user.is_maker %}
    <a class ="btn btn-primary" href ="{% url 'files:create' %}">Upload File</a></br>
    {% endif %}
    <div class='row row-1'>
        <div clas='col-2'>
            <a class = 'btn btn-primary' href ="{% url 'home' %}">New User</a></br>
        </div>
  
        <div class='col-10'style="text-align:right";>
            <a class = 'btn btn-primary' href ="{% url 'accounts:logout' %}">LogOut</a></br>
        </div>
    </div>
    <div class="main-comments">
      <h2> Title: <b>{{ post.title }}</b></h2>
      <img src= "/media/{{ post.file }}">
      <!-- <p>File: <a href="/media/{{ post.file }}">{{ post.file | safe }}</a></p> -->
     <p><b>{{ post.author }} | {{ post.created_on }}</b></p
  
  
    <h2><b>{{ comments.count }} Comments list</b></h2>
  
      {% for comment in comments %}
      <hr>
      <p >
        {{ comment.body }}
      </p>
        <span>
          <b>{{ comment.name }}</b>
        </span>
        <span>
          {{ comment.created_on }}
        </span>
    
      <hr>
      {% endfor %}
    
      {% if new_comment %}
    
    
      Your comment is awaiting moderation
    
      {% else %}
    
      <h2>Leave a comment</h2>
      <div class="card">
        <form method="post">
          {% csrf_token %}
            <div class="form-group">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Your Name" name="name" required>
            </div>
            <div class="form-group">
              <label>Comments</label>
              <input type="textarea" class="form-control" placeholder="Comments..." name="body" required>
            </div>
    
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    </div>
    
    
    {% endif %}
  </div>
</div>
  
 
{% endblock %}

mediafile/templates/mediafile/list.html
{% extends 'accounts/base.html' %}

{% block content %}

    
<style>
    hr{
        color: white;
    }

    h1{
        text-align: center;
    }

    h1, li, a{font-family:Times New Roman;}
    .btn{
        margin:5px;
    }
    img{
        width: 350px;
        height: 400px;
        text-align: center;
        margin-left:20vw;
    }
    video{
        text-align: center;
        margin-left:20vw;


    }
    embed{

        text-align:center;
        margin-left:10vw;
    }
    .col-9{
        margin-top: 60px;
        margin-left: 25vw;
        position:static;
    }
    .col-3{
    margin-top: 4vw;
    position: fixed;
    }

    .row-1{
        margin-left: 2px;
    }
</style>
<div class='row'>
    <div class="col-3">
        {% block sidebar %} 
        {% include 'accounts/sidebar.html' %}
        {% endblock %}
    </div>
    <div class="col-9">
        <h1>Lists of all Files</h1>
        {% if request.user.is_maker %}
        <a class ="btn btn-primary" href ="{% url 'files:create' %}">Upload File</a></br>
        {% endif %}
        <div class='row row-1' >
            <div clas='col-2'>
                <a class = 'btn btn-primary' href ="{% url 'accounts:signupmaker' %}">New User</a></br>
            </div>
            <div class='col-10'style="text-align:right";>
                <a class = 'btn btn-primary' href ="{% url 'accounts:logout' %}">LogOut</a></br>
            </div>
        </div>
        <hr>
        {% for u in data %}
        <div class="post">
            <h2> Title: <b>{{ u.title }}</b></h2>
            {% if u.Type == 2 %}
                <embed src='/media/{{u.file}}' type="application/pdf" width='680' height="560" frameborder="0"/>
            {% elif u.Type == 3 %}
                <video width="350" height="240" controls>
                    <source src="/media/{{u.file}}" type="video/mp4">
                  </video>
            {% else %}
                <img src = '/media/{{u.file}}'>
             {% endif %}
                <p>
                File: <a class="btn btn-primary" href="/media/{{u.file}}">{{ u.file }}</a>
                File Name:{{u.file }}</b>
                Created By:<b>{{ u.author }}</b>
                Created At: <b>{{ u.created_on }}</b>
                {% if request.user.is_checker %}
                <a class='btn btn-primary' href="{% url 'files:update' u.id %}">update</a>
                <a class= 'btn btn-primary' href="{% url 'files:delete' u.id %}">delete</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'files:detail' u.id %}">Detail &rarr;</a>
            </p>
       <hr>
        </div>
        {% endfor %}
        <hr>
    </div>
</div>




{% endblock %}

mediafile/templates/mediafile/update.html
<h1>Update File</h1>
<form method='post' enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type='submit'>Submit</button>
</form>